return {
    ensure_installed = {
        -- LSPs
        "autotools-language-server",
        "typescript-language-server",
        "bash-language-server",
        "basedpyright",
        "docker-compose-language-service",
        "dockerfile-language-server",
        "jedi-language-server",
        "gopls",
        "json-lsp",
        "rust-analyzer",
        "codelldb",
        "taplo",
        "yaml-language-server",
        "lua-language-server",
        "ansible-language-server",
        -- REST
        "beautysh",
        "gofumpt",
        "google-java-format",
        "luacheck",
        "prettier",
        "prettierd",
        "stylua",
        "woke",
        "yamlfix",
        "ansible-lint",
    },
    auto_update = true,
}
